services:
  web:
    image: php:8.5-apache
    build: .
    container_name: scarif_dev
    ports:
      - "5080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=10.177.206.126
      - DB_PORT=5306
      - DB_NAME=telemetry_db
      - DB_USER=student_user
      - DB_PASSWORD=Password123!
    restart: unless-stopped